from environment.AmazonEnv import AmazonEnv
from environment.BikeShareEnv import BikeShareEnv
from environment.HousePriceEnv import HousePriceEnv
from environment.TitanicEnv import TitanicEnv
from environment.CustomerSatisfactionEnv import CustomerSatisfactionEnv